config/routes.rb
Rails.application.routes.draw do
  root to: 'store#index'
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'pack of 5 stickers',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :root
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/charges/create.html.erb
<h2>Thanks for your purchase!</h2>

<h3>Your stickers are on the way!</h3>

<%= image_tag 'https://s3-us-west-2.amazonaws.com/stickers.win/thanks.gif' %>

<h3><%= link_to 'Buy more stickers!', :root %><h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🔥 stickers.win 🚀</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <h1><%= link_to '🔥 stickers.win 🚀', :root %></h1>    
      <%= yield %>
    </div>
  </body>
</html>

app/views/store/index.html.erb
<div class='product'>
  <h2>Pack of 5 stickers for $5</h2>
  <h3>Free shipping anywhere in the world!</h3>
  <div class='sticker'>
    <%= image_tag('https://s3-us-west-2.amazonaws.com/stickers.win/reactallthethings.png', alt: 'REACT ALL THE THINGS') %>
  </div>

  <%= form_tag charges_path, class: 'payment-form' do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
    </article>

    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Pack of 5 stickers"
            data-label="Buy Now"
            data-amount="500"
            data-locale="auto"></script>
  <% end %>

</div>